repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-xml
        -   id: debug-statements
        -   id: double-quote-string-fixer
        -   id: name-tests-test
            args: ["--pytest-test-first"]
        -   id: requirements-txt-fixer
        -   id: check-added-large-files
        -   id: check-case-conflict
        -   id: check-merge-conflict
        -   id: check-symlinks
        -   id: detect-private-key
        -   id: check-json
        -   id: check-toml
        -   id: requirements-txt-fixer
        -   id: sort-simple-yaml

  -   repo: https://github.com/asottile/setup-cfg-fmt
      rev: v2.2.0
      hooks:
        -   id: setup-cfg-fmt
  -   repo: https://github.com/asottile/reorder_python_imports
      rev: v3.9.0
      hooks:
        -   id: reorder-python-imports
  -   repo: https://github.com/asottile/add-trailing-comma
      rev: v2.4.0
      hooks:
        -   id: add-trailing-comma
  -   repo: https://github.com/asottile/pyupgrade
      rev: v3.3.1
      hooks:
        -   id: pyupgrade
  -   repo: https://github.com/pre-commit/mirrors-autopep8
      rev: v2.0.2
      hooks:
        -   id: autopep8
  -   repo: https://github.com/PyCQA/flake8
      rev: 6.0.0
      hooks:
        -   id: flake8
            entry: pflake8
            additional_dependencies: [
              'flake8-blind-except',
              'flake8-bugbear',
              'flake8-sfs',
              'flake8-comprehensions',
              'flake8-implicit-str-concat',
              'pyproject-flake8',
            ]
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.0.1
      hooks:
        -   id: mypy
            additional_dependencies: [types-all]
  -   repo: https://github.com/pycqa/pydocstyle
      rev: 6.3.0
      hooks:
        -   id: pydocstyle
            additional_dependencies: ["tomli"]
  -   repo: https://github.com/asottile/dead
      rev: v1.5.0
      hooks:
        -   id: dead
  -   repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.10.0
      hooks:
          -   id: python-check-blanket-noqa
          -   id: python-check-mock-methods
          -   id: python-check-blanket-type-ignore
          -   id: python-no-eval
          -   id: python-no-log-warn
          -   id: python-use-type-annotations
          -   id: text-unicode-replacement-char
  -   repo: https://github.com/python-poetry/poetry
      rev: '1.5.1'
      hooks:
        - id: poetry-check
        - id: poetry-lock
