image: zivgitlab.wwu.io/ml-de/teaching/ps-housetech/ps-housetech-backend:python3.11.3

job:
  tags:
    - jim

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  POETRY_CACHE_DIR: "$CI_PROJECT_DIR/.cache/poetry"
  PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"

cache:
  - key:
      files:
        - poetry.lock
    paths:
      - .venv
      - .cache/pip
      - .cache/poetry
      - $PIP_CACHE_DIR
      - $POETRY_CACHE_DIR
  - key:
      files:
        - pre-commit-config.yaml
    paths:
      - $PRE_COMMIT_HOME

before_script:
  - pip install --upgrade pip
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - poetry install --no-root
  - source `poetry env info --path`/bin/activate

include:
  - ".gitlab/*.yaml"
